# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# 
# This action will create a new Pull Request containing the latest changes from the base Template repository.
# If this action fails, it may require a manual sync to be performed. Use the following command
# git pull <insert-pat>@github.com/microsoft/commercial-marketplace-offer-solution \
#  --allow-unrelated-histories \
#  --squash \
#  --strategy=recursive \
#  -X theirs
#
# Note that the 'secrets.github_token' token has specific permissions.
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
#
# You may need to create a Personal Access Token (PAT) and add it as a secret (ex: PAT) to use in your workflow. https://github.com/settings/tokens
# Then replace ${{ secrets.github_token }} with ${{ secrets.PAT }}
#
# Find more details about the github_token here https://docs.github.com/en/actions/security-guides/automatic-token-authentication#granting-additional-permissions
on:
  workflow_dispatch:
# Uncomment this section to run the action nightly
#  schedule:
#    - cron: '0 0 * * *'  # every day at midnight

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:          
          token: ${{ secrets.github_token }}
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.4.2-draft
        with:
          github_token: ${{ secrets.github_token }}
          source_repo_path: microsoft/commercial-marketplace-offer-solution
